spring:
  application:
    name: manage-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qtj_manage?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # 打印 SQL 核心配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/qtj/manageserver/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0

files:
  upload:
    # 本地真实存储绝对路径
    local-path: D:/temp/upload/
    # 浏览器访问虚拟前缀
    virtual-path: /upload/
  download:
    path: D:/temp/download

jwt:
  secret: auth-system-secret-key-2026-1234
  expiration: 86400000 # 24小时